---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # --- BGP ---
  - ../base/bgp_advertise.yaml
  - bgp_cluster.yaml
  - bgp_peer.yaml
  - lb-ip.yaml
  # --- Host Firewall ---
  - ../base/01-controlplane.yaml
  - ../base/02-ssh.yaml
  # --- Prefix Lists ---
  - ../base/ssh-gw-hosts.yaml
  - ../base/snmp-pollers.yaml
  - ../base/aap-job-runners.yaml
  - node-pool.yaml
  - other-pool.yaml
